package com.visfull.system.domain;

// Generated 2012-8-1 16:40:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LogUserLogin generated by hbm2java
 */
@Entity
@Table(name = "log_user_login")
public class LogUserLogin implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;
    private long id;
    private Long userId;
    private String userName;
    private String userType;
    private Date loginTime;

    public LogUserLogin() {
    }

    public LogUserLogin(long id) {
        this.id = id;
    }

    public LogUserLogin(long id, Long userId, String userName, String userType, Date loginTime) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.userType = userType;
        this.loginTime = loginTime;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "user_id")
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "user_name", length = 64)
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Column(name = "user_type", length = 32)
    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "login_time", length = 19)
    public Date getLoginTime() {
        return this.loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

}
