package com.visfull.system.domain;

// Generated 2012-8-1 16:40:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.visfull.system.emnu.DictType;

/**
 * SystemDict generated by hbm2java
 */
@Entity
@Table(name = "system_dict")
public class SystemDict implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long id;
    private DictType dictType;
    private String dictName;
    private String dictCode;
    private String dictDescribe;
    private Date createDate;

    public SystemDict() {
    }

    public SystemDict(long id) {
        this.id = id;
    }

    public SystemDict(long id, DictType dictType, String dictName, String dictCode, String dictDescribe, Date createDate) {
        this.id = id;
        this.dictType = dictType;
        this.dictName = dictName;
        this.dictCode = dictCode;
        this.dictDescribe = dictDescribe;
        this.createDate = createDate;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }
    
	@Enumerated(EnumType.STRING)
    @Column(name = "dict_type", length = 32)
    public DictType getDictType() {
        return this.dictType;
    }

    public void setDictType(DictType dictType) {
        this.dictType = dictType;
    }

    @Column(name = "dict_name", length = 64)
    public String getDictName() {
        return this.dictName;
    }

    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    @Column(name = "dict_code", length = 32)
    public String getDictCode() {
        return this.dictCode;
    }

    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    @Column(name = "dict_describe")
    public String getDictDescribe() {
        return this.dictDescribe;
    }

    public void setDictDescribe(String dictDescribe) {
        this.dictDescribe = dictDescribe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    
    
}
