package com.visfull.system.domain;

// Generated 2012-8-1 16:40:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRole implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long id;
    private Long autId;
    private String roleName;
    private String roleType;
    private String roleDescribe;
    private Date createDate;
    private Set<AuthUser> users;
    private Set<AuthResource> resources;
    public UserRole() {
    }

    public UserRole(long id) {
        this.id = id;
    }

    public UserRole(long id, Long autId, String roleName, String roleType, String roleDescribe, Date createDate) {
        this.id = id;
        this.autId = autId;
        this.roleName = roleName;
        this.roleType = roleType;
        this.roleDescribe = roleDescribe;
        this.createDate = createDate;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "aut_id")
    public Long getAutId() {
        return this.autId;
    }

    public void setAutId(Long autId) {
        this.autId = autId;
    }

    @Column(name = "role_name", length = 64)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "role_type", length = 32)
    public String getRoleType() {
        return this.roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    @Column(name = "role_describe")
    public String getRoleDescribe() {
        return this.roleDescribe;
    }

    public void setRoleDescribe(String roleDescribe) {
        this.roleDescribe = roleDescribe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "auth_user_role", catalog = "bingo", joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
    public Set<AuthUser> getUsers() {
        return users;
    }

    public void setUsers(Set<AuthUser> users) {
        this.users = users;
    }
    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "auth_role_map", catalog = "bingo", joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "resource_id", nullable = false, updatable = false) })
    public Set<AuthResource> getResources() {
        return resources;
    }

    public void setResources(Set<AuthResource> resources) {
        this.resources = resources;
    }
}
