package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * BzBlackWhite generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_black_white")
public class BzBlackWhite implements java.io.Serializable {
	
	@Expose
	private Long id;
	@Expose
	private String phone;
	@Expose
	private PhoneType type;
	@Expose
	private Date createDate;

	public BzBlackWhite() {
	}

	public BzBlackWhite(String phone, PhoneType type, Date createDate) {
		this.phone = phone;
		this.type = type;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "phone", length = 32)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "type", length = 10)
	public PhoneType getType() {
		return this.type;
	}

	public void setType(PhoneType type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	public enum PhoneType implements IEnumDisplay{
       BLACK("黑名单") ,WHITE("白名单");
       private String msg;
       
       private PhoneType(String msg){
           this.msg = msg;
       }
        public String getDisplayName() {
            return this.msg;
        }
	    
	}
}
