package com.visfull.bz.domain;

// Generated 2013-1-11 11:28:59 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;
import com.visfull.bz.emnu.CallType;

/**
 * BzCallRecord generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_call_record")
public class BzCallRecord implements java.io.Serializable {

	/**
	 * 
	 */
	@Expose
	private long id;
	@Expose
	private String callingNum;
	@Expose
	private String calledNum;
	@Expose
	private Long callingTime;
	@Expose
	private CallType callType;
	@Expose
	private Long duration;
	@Expose
	private Date createDate;

	public BzCallRecord() {
	}

	public BzCallRecord(long id) {
		this.id = id;
	}

	public BzCallRecord(long id, String callingNum, String calledNum,
			Long callingTime, Date createDate) {
		this.id = id;
		this.callingNum = callingNum;
		this.calledNum = calledNum;
		this.callingTime = callingTime;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "calling_num", length = 10)
	public String getCallingNum() {
		return this.callingNum;
	}

	public void setCallingNum(String callingNum) {
		this.callingNum = callingNum;
	}

	@Column(name = "called_num", length = 10)
	public String getCalledNum() {
		return this.calledNum;
	}

	public void setCalledNum(String calledNum) {
		this.calledNum = calledNum;
	}

	@Column(name = "calling_time")
	public Long getCallingTime() {
		return this.callingTime;
	}

	public void setCallingTime(Long callingTime) {
		this.callingTime = callingTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Enumerated(EnumType.STRING)
	@Column(name = "call_type")
	public CallType getCallType() {
		return callType;
	}

	public void setCallType(CallType callType) {
		this.callType = callType;
	}
	@Column(name = "duration")
	public Long getDuration() {
		return duration;
	}
	public void setDuration(Long duration) {
		this.duration = duration;
	}

}
