package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.google.gson.annotations.Expose;

/**
 * BzCusomerBinder generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_customer_binder")
public class BzCustomerBinder implements java.io.Serializable {
	
	@Expose
	private Long id;
	@Expose
	private Long customerId;
	@Expose
	private String customerName;
	@Expose
	private String customerPhone;
	@Expose
	private Long targetId;
	@Expose
	private String targetCode;
	@Expose
	private String targetName;
	@Expose
	private TargetType targetType;
	@Expose
	private String serviceInfo;
	@Expose
	private Date serviceDate;
	@Expose
	private Long duration;
	@Expose
	private Date createDate;
	@Expose
	private List<BzPoster> posters;
	

	public BzCustomerBinder() {
	}

	public BzCustomerBinder(Long customerId, String customerName,
			String customerPhone, Long targetId, String targetName,
			Date createDate) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.targetId = targetId;
		this.targetName = targetName;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "customer_id")
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_name", length = 64)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_phone", length = 32)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "target_id")
	public Long getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Long targetId) {
		this.targetId = targetId;
	}

	@Column(name = "target_name")
	public String getTargetName() {
		return this.targetName;
	}

	public void setTargetName(String targetName) {
		this.targetName = targetName;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "target_type", length = 10)
	public TargetType getTargetType() {
		return targetType;
	}

	public void setTargetType(TargetType targetType) {
		this.targetType = targetType;
	}
	
	@Column(name = "service_info")
	public String getServiceInfo() {
		return serviceInfo;
	}

	public void setServiceInfo(String serviceInfo) {
		this.serviceInfo = serviceInfo;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "service_date", length = 19)
	public Date getServiceDate() {
		return serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Column(name = "duration")
	public Long getDuration() {
		return duration;
	}
	
	public void setDuration(Long duration) {
		this.duration = duration;
	}
	
	
	
	@Column(name = "target_code")
	public String getTargetCode() {
		return targetCode;
	}

	public void setTargetCode(String targetCode) {
		this.targetCode = targetCode;
	}
	@Transient
	public List<BzPoster> getPosters() {
		return posters;
	}

	public void setPosters(List<BzPoster> posters) {
		this.posters = posters;
	}




	public enum TargetType implements IEnumDisplay{
		SP("运营商"),CP("服务提供商"),SERVER("服务人员");
		private String msg ;
		private TargetType(String msg){
			this.msg = msg;
		}
		public String getDisplayName() {
			return msg;
		}
	}

}
