package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * BzCustomerHistory generated by hbm2java
 */
@Entity
@Table(name = "bz_customer_history")
public class BzCustomerHistory implements java.io.Serializable {

	@Expose
	private Long id;
	@Expose
	private String customerPhone;
	@Expose
	private String customerName;
	@Expose
	private Long operatorId;
	@Expose
	private String operatorName;
	@Expose
	private Long providerId;
	@Expose
	private String providerName;
	@Expose
	private Long serverId;
	@Expose
	private String serverName;
	@Expose
	private Date createDate;

	public BzCustomerHistory() {
	}

	public BzCustomerHistory(String customerPhone, String customerName,
			Long operatorId, String operatorName, Long providerId,
			String providerName, Long serverId, String serverName,
			Date createDate) {
		this.customerPhone = customerPhone;
		this.customerName = customerName;
		this.operatorId = operatorId;
		this.operatorName = operatorName;
		this.providerId = providerId;
		this.providerName = providerName;
		this.serverId = serverId;
		this.serverName = serverName;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "customer_phone", length = 32)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "customer_name", length = 64)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "operator_id")
	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "operator_name")
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	@Column(name = "provider_id")
	public Long getProviderId() {
		return this.providerId;
	}

	public void setProviderId(Long providerId) {
		this.providerId = providerId;
	}

	@Column(name = "provider_name")
	public String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "server_id")
	public Long getServerId() {
		return this.serverId;
	}

	public void setServerId(Long serverId) {
		this.serverId = serverId;
	}

	@Column(name = "server_name")
	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
