package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;
import com.visfull.bz.emnu.Gender;

/**
 * BzCustomer generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_customer")
public class BzCustomer implements java.io.Serializable {
	
	@Expose
	private Long id;
	@Expose
	private String name;
	private String pwd;
	@Expose
	private String age;
	@Expose
	private Gender gender;
	@Expose
	private String bindPhone;
	@Expose
	private String residence;
	@Expose
	private Date createDate;

	public BzCustomer() {
	}

	public BzCustomer(String name, String age, Gender gender, String bindPhone,
			Date createDate) {
		this.name = name;
		this.age = age;
		this.gender = gender;
		this.bindPhone = bindPhone;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", length = 10)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "gender")
	public Gender getGender() {
		return this.gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	@Column(name = "bind_phone", length = 32)
	public String getBindPhone() {
		return this.bindPhone;
	}

	public void setBindPhone(String bindPhone) {
		this.bindPhone = bindPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	@Column(name = "pwd")
	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	@Column(name = "residence")
	public String getResidence() {
		return residence;
	}

	public void setResidence(String residence) {
		this.residence = residence;
	}
	
}
