package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * BzOperator generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_operator")
public class BzOperator implements java.io.Serializable {
	
	@Expose
	private long id;
	@Expose
	private String opCode;
	@Expose
	private String opName;
	private String opPwd;
	@Expose
	private String opHours;
	@Expose
	private String opPoster;
	@Expose
	private String opHomepage;
	@Expose
	private String opPhone;
	@Expose
	private String opAddress;
	@Expose
	private String opMotto;
	@Expose
	private String opServiceintroduce;
	@Expose
	private OpStatus status;
	@Expose
	private Date initDate;
	@Expose
	private Date joinDate;
	@Expose
	private Date modifyTime;
	@Expose
	private Date createDate;

	public BzOperator() {
	}

	public BzOperator(long id, Date modifyTime) {
		this.id = id;
		this.modifyTime = modifyTime;
	}

	public BzOperator(long id, String opCode, String opName, String opPhone,
			String opServiceintroduce, OpStatus status, Date modifyTime,
			Date createDate) {
		this.id = id;
		this.opCode = opCode;
		this.opName = opName;
		this.opPhone = opPhone;
		this.opServiceintroduce = opServiceintroduce;
		this.status = status;
		this.modifyTime = modifyTime;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "op_code", length = 32 )
	public String getOpCode() {
		return this.opCode;
	}

	public void setOpCode(String opCode) {
		this.opCode = opCode;
	}

	@Column(name = "op_name")
	public String getOpName() {
		return this.opName;
	}

	public void setOpName(String opName) {
		this.opName = opName;
	}

	@Column(name = "op_phone", length = 1024)
	public String getOpPhone() {
		return this.opPhone;
	}

	public void setOpPhone(String opPhone) {
		this.opPhone = opPhone;
	}

	@Column(name = "op_serviceintroduce", length = 65535)
	public String getOpServiceintroduce() {
		return this.opServiceintroduce;
	}

	public void setOpServiceintroduce(String opServiceintroduce) {
		this.opServiceintroduce = opServiceintroduce;
	}
	@Enumerated(EnumType.STRING)
	@Column(name = "status", length = 10)
	public OpStatus getStatus() {
		return this.status;
	}

	public void setStatus(OpStatus status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", nullable = false, length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Column(name = "op_pwd")
	public String getOpPwd() {
		return opPwd;
	}

	public void setOpPwd(String opPwd) {
		this.opPwd = opPwd;
	}
	
	@Column(name = "op_hours")
	public String getOpHours() {
		return opHours;
	}

	public void setOpHours(String opHours) {
		this.opHours = opHours;
	}
	
	@Column(name ="op_poster")
	public String getOpPoster() {
		return opPoster;
	}

	public void setOpPoster(String opPoster) {
		this.opPoster = opPoster;
	}
	
	@Column(name = "op_homepage")
	public String getOpHomepage() {
		return opHomepage;
	}

	public void setOpHomepage(String opHomepage) {
		this.opHomepage = opHomepage;
	}
	
	@Column(name = "op_address")
	public String getOpAddress() {
		return opAddress;
	}

	public void setOpAddress(String opAddress) {
		this.opAddress = opAddress;
	}
	@Column(name = "op_motto")
	public String getOpMotto() {
		return opMotto;
	}
	

	public void setOpMotto(String opMotto) {
		this.opMotto = opMotto;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "init_date", length = 19)
	public Date getInitDate() {
		return initDate;
	}

	public void setInitDate(Date initDate) {
		this.initDate = initDate;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "join_date", length = 19)
	public Date getJoinDate() {
		return joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	public enum OpStatus implements IEnumDisplay{
		NORMAL("正常"),STOP("停用");
		private String msg ;
		private OpStatus(String msg){
			this.msg = msg;
		}
		public String getDisplayName() {
			return msg;
		}
	}

}
