package com.visfull.bz.domain;

// Generated 2013-1-24 18:26:49 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;
import com.visfull.bz.emnu.TargetType;

/**
 * BzPoster generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_poster")
public class BzPoster implements java.io.Serializable {
	
	@Expose
	private Long id;
	@Expose
	private Long owner;
	@Expose
	private String posterUrl;
	@Expose
	private String posterDesc;
	@Expose
	private Date createDate;
	@Expose
	private TargetType ownerType;
	public BzPoster() {
	}

	public BzPoster(Long owner, String posterUrl, String posterDesc,
			Date createDate) {
		this.owner = owner;
		this.posterUrl = posterUrl;
		this.posterDesc = posterDesc;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "owner")
	public Long getOwner() {
		return this.owner;
	}

	public void setOwner(Long owner) {
		this.owner = owner;
	}

	@Column(name = "poster_url", length = 1024)
	public String getPosterUrl() {
		return this.posterUrl;
	}

	public void setPosterUrl(String posterUrl) {
		this.posterUrl = posterUrl;
	}

	@Column(name = "poster_desc", length = 65535)
	public String getPosterDesc() {
		return this.posterDesc;
	}

	public void setPosterDesc(String posterDesc) {
		this.posterDesc = posterDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	@Enumerated(EnumType.STRING)
	@Column(name = "owner_type")
	public TargetType getOwnerType() {
		return ownerType;
	}

	public void setOwnerType(TargetType ownerType) {
		this.ownerType = ownerType;
	}
	
}
