package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicUpdate;

import com.google.gson.annotations.Expose;
import com.visfull.bz.emnu.Gender;

/**
 * BzServer generated by hbm2java
 */
@SuppressWarnings("serial")
@DynamicUpdate(true)
@Entity
@Table(name = "bz_server")
public class BzServer implements java.io.Serializable {

	@Expose
	private long id;
	@Expose
	private String serverName;
	@Expose
	private String serverCode;
	private String pwd;
	@Expose
	private Gender gender;
	@Expose
	private int age;
	@Expose
	private String identity;
	@Expose
	private String province;
	@Expose
	private String phone;
	@Expose
	private String skillIntroduce;
	@Expose
	private long spId;
	@Expose
	private String spName;
	@Expose
	private ServerStatus status;
	@Expose
	private Date modifyTime;
	@Expose
	private Date createDate;
	@Expose
	private List<BzPoster> posters; 

	public BzServer() {
	}

	public BzServer(long id, Date modifyTime) {
		this.id = id;
		this.modifyTime = modifyTime;
	}

	public BzServer(long id, String serverName, String phone,
			String skillIntroduce, ServerStatus status, Date modifyTime,
			Date createDate) {
		this.id = id;
		this.serverName = serverName;
		this.phone = phone;
		this.skillIntroduce = skillIntroduce;
		this.status = status;
		this.modifyTime = modifyTime;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "server_name")
	public String getServerName() {
		return this.serverName;
	}

	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "skill_introduce", length = 65535)
	public String getSkillIntroduce() {
		return this.skillIntroduce;
	}

	public void setSkillIntroduce(String skillIntroduce) {
		this.skillIntroduce = skillIntroduce;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "status", length = 10)
	public ServerStatus getStatus() {
		return this.status;
	}

	public void setStatus(ServerStatus status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time", nullable = false, length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "sp_id")
	public long getSpId() {
		return spId;
	}

	public void setSpId(long spId) {
		this.spId = spId;
	}

	@Column(name = "pwd")
	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "gender")
	public Gender getGender() {
		return gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	@Column(name = "age")
	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "identity")
	public String getIdentity() {
		return identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	@Column(name = "province")
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "server_code")
	public String getServerCode() {
		return serverCode;
	}

	public void setServerCode(String serverCode) {
		this.serverCode = serverCode;
	}
	
	
	@Column(name = "sp_name")
	public String getSpName() {
		return spName;
	}

	public void setSpName(String spName) {
		this.spName = spName;
	}
	
	@Transient
	public List<BzPoster> getPosters() {
		return posters;
	}

	public void setPosters(List<BzPoster> posters) {
		this.posters = posters;
	}



	public enum ServerStatus implements IEnumDisplay {
		NORMAL("正常"), STOP("停用");
		private String msg;

		private ServerStatus(String msg) {
			this.msg = msg;
		}

		public String getDisplayName() {
			return msg;
		}
	}

}
