package com.visfull.bz.domain;

// Generated 2012-11-9 15:20:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.gson.annotations.Expose;

/**
 * BzSignIn generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "bz_sign_in")
public class BzSignIn implements java.io.Serializable {
	
	@Expose
	private Long id;
	@Expose
	private String signinPhone;
	@Expose
	private Date signinTime;

	public BzSignIn() {
	}

	public BzSignIn(String signinPhone, Date signinTime) {
		this.signinPhone = signinPhone;
		this.signinTime = signinTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "signin_phone", length = 32)
	public String getSigninPhone() {
		return this.signinPhone;
	}

	public void setSigninPhone(String signinPhone) {
		this.signinPhone = signinPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "signin_time", length = 19)
	public Date getSigninTime() {
		return this.signinTime;
	}

	public void setSigninTime(Date signinTime) {
		this.signinTime = signinTime;
	}

}
