package com.visfull.bz.domain;

// Generated 2013-4-8 16:07:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * County generated by hbm2java
 */
@Entity
@Table(name = "county")
public class County implements java.io.Serializable {

	private int id;
	private String name;
	private String code;
	private int cityId;

	public County() {
	}

	public County(int id, String name, String code, int cityId) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.cityId = cityId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CityID", nullable = false)
	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

}
