package com.visfull.bz.domain;

// Generated 2013-4-8 16:07:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Town generated by hbm2java
 */
@Entity
@Table(name = "town")
public class Town implements java.io.Serializable {

	private int id;
	private String name;
	private String code;
	private int countyId;

	public Town() {
	}

	public Town(int id, String name, String code, int countyId) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.countyId = countyId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "CountyID", nullable = false)
	public int getCountyId() {
		return this.countyId;
	}

	public void setCountyId(int countyId) {
		this.countyId = countyId;
	}

}
