package com.visfull.bz.domain;

// Generated 2013-4-8 16:07:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Village generated by hbm2java
 */
@Entity
@Table(name = "village")
public class Village implements java.io.Serializable {

	private int id;
	private String name;
	private String code;
	private int townId;

	public Village() {
	}

	public Village(int id, String name, String code, int townId) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.townId = townId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", nullable = false, length = 3)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "TownID", nullable = false)
	public int getTownId() {
		return this.townId;
	}

	public void setTownId(int townId) {
		this.townId = townId;
	}

}
